import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    // Verify the user is admin_court or magistrate
    const { data: profile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();

    if (!profile || !["admin_court", "magistrate"].includes(profile.role)) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    const body = await request.json();
    const { case_id } = body;

    if (!case_id) {
      return NextResponse.json({ error: "case_id is required" }, { status: 400 });
    }

    // Fetch case details
    const { data: caseRow, error: caseError } = await supabase
      .from("cases")
      .select("id, case_number, title, case_type, defendant_name, defendant_email, defendant_phone, defendant_address, defendant_id, status, plaintiff:profiles!plaintiff_id(full_name)")
      .eq("id", case_id)
      .single();

    if (caseError || !caseRow) {
      return NextResponse.json({ error: "Case not found" }, { status: 404 });
    }

    if (!["registered", "summon_issued"].includes(caseRow.status)) {
      return NextResponse.json(
        { error: "Case must be in 'registered' status to issue summon" },
        { status: 400 }
      );
    }

    if (!caseRow.defendant_name) {
      return NextResponse.json(
        { error: "No defendant information on this case" },
        { status: 400 }
      );
    }

    // Build the summon message
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
    const registerUrl = `${appUrl}/register`;

    const plaintiff = caseRow.plaintiff as unknown as { full_name: string } | null;

    const summonMessage = `
COURT SUMMON NOTICE

To: ${caseRow.defendant_name}
${caseRow.defendant_address ? `Address: ${caseRow.defendant_address}` : ""}

Case Number: ${caseRow.case_number}
Case Title: ${caseRow.title}
Case Type: ${caseRow.case_type.charAt(0).toUpperCase() + caseRow.case_type.slice(1)}
Filed By: ${plaintiff?.full_name || "Plaintiff"}

You are hereby summoned to appear before the Court in connection with the above-referenced case. You are required to:

1. Register on the Civilex platform: ${registerUrl}
2. After registering, use your personal claim link to access this case
3. Hire a lawyer or choose to self-represent
4. Submit your response and any relevant documents within 30 days of receiving this notice

Failure to respond may result in an ex-parte decision against you.

This is an official court communication generated by the Civilex Judiciary Management System.
`.trim();

    // Generate a defendant claim token (valid 90 days) for self-linking
    const claimToken = crypto.randomUUID().replace(/-/g, "") + crypto.randomUUID().replace(/-/g, "");
    const claimExpires = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString();

    // Update case with summon tracking + claim token
    await supabase
      .from("cases")
      .update({
        status: "summon_issued",
        summon_sent_at: new Date().toISOString(),
        summon_sent_by: user.id,
        defendant_claim_token: claimToken,
        defendant_claim_expires_at: claimExpires,
      })
      .eq("id", case_id)
      .eq("status", "registered");

    const claimUrl = `${appUrl}/summon/${case_id}?token=${claimToken}`;

    // Log activity
    await supabase.from("case_activity_log").insert({
      case_id,
      actor_id: user.id,
      action: "summon_issued",
      details: {
        defendant: caseRow.defendant_name,
        defendant_email: caseRow.defendant_email,
        method: caseRow.defendant_email ? "email_and_notification" : "notification_only",
      },
    });

    // Send in-app notification to defendant if they have an account
    if (caseRow.defendant_id) {
      await supabase.from("notifications").insert({
        user_id: caseRow.defendant_id,
        title: "Court Summon Issued",
        message: `You have been summoned in case "${caseRow.title}" (${caseRow.case_number}). Please respond within 30 days by hiring a lawyer and submitting your response. View case: ${claimUrl}`,
        type: "summon_issued",
        reference_type: "case",
        reference_id: case_id,
      });
    }

    // Notify plaintiff about summon issuance
    const { data: plaintiffCase } = await supabase
      .from("cases")
      .select("plaintiff_id")
      .eq("id", case_id)
      .single();

    if (plaintiffCase?.plaintiff_id) {
      await supabase.from("notifications").insert({
        user_id: plaintiffCase.plaintiff_id,
        title: "Summon Issued to Defendant",
        message: `A court summon has been issued to the defendant in your case "${caseRow.title}" (${caseRow.case_number}).`,
        type: "case_status_changed",
        reference_type: "case",
        reference_id: case_id,
      });
    }

    // Notify assigned lawyers
    const { data: assignments } = await supabase
      .from("case_assignments")
      .select("lawyer_id")
      .eq("case_id", case_id)
      .eq("status", "accepted");

    if (assignments) {
      for (const a of assignments) {
        await supabase.from("notifications").insert({
          user_id: a.lawyer_id,
          title: "Summon Issued",
          message: `Court summon issued to defendant in case "${caseRow.title}" (${caseRow.case_number}).`,
          type: "case_status_changed",
          reference_type: "case",
          reference_id: case_id,
        });
      }
    }

    // Email sending — In production, integrate with an email service (Resend, SendGrid, etc.)
    // For this FYP, we log the email content and return it in the response for demo purposes.
    let emailSent = false;
    if (caseRow.defendant_email) {
      if (process.env.NODE_ENV === "production" && process.env.RESEND_API_KEY) {
        // Production email sending would go here
        // e.g., await resend.emails.send({ ... })
        emailSent = true;
      } else {
        // Demo mode — log the email
        console.log("=== SUMMON EMAIL (Demo Mode) ===");
        console.log(`To: ${caseRow.defendant_email}`);
        console.log(`Subject: Court Summon - Case ${caseRow.case_number}`);
        console.log(summonMessage);
        console.log("=== END SUMMON EMAIL ===");
      }
    }

    return NextResponse.json({
      success: true,
      summon: {
        defendant_name: caseRow.defendant_name,
        defendant_email: caseRow.defendant_email,
        email_sent: emailSent,
        notification_sent: !!caseRow.defendant_id,
        register_url: registerUrl,
        claim_url: claimUrl,
      },
      // Include summon text in non-production for demo
      ...(process.env.NODE_ENV !== "production" ? { summon_text: summonMessage } : {}),
    });
  } catch (err) {
    console.error("Summon send error:", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
